### ISSUE TITLE
Are these Guidelines still relevant?

### ISSUE THREAD

**Issue by echeadle** [GDSSecurity/Docker-Secure-Deployment-Guidelines#5]
This is a very interesting set of guidelines.  In it, I saw Docker version 1.3 and 1.2 mentioned.  With the release of 1.13, are these guidelines still relevant?  Would any of the guidelines change?

**Comment by qgrosperrin** [comment]
The guidelines are not actively maintained. I would recommend the very good CIS benchmark resources at : https://benchmarks.cisecurity.org/downloads/show-single/index.cfm?file=docker13.100
